### ISSUE TITLE
Lose Editor focus when set Window visible

### ISSUE THREAD

**Issue by 12Tall** [SavenkovIgor/QmlSandboxExtension#54]
Dear developer, you make a great tool. but there is a small point maybe you can improve afterwards：  
In the following qml file, it will lose the focus of the editor when I update the source file.    
```qml{5}
import QtQuick 2.14  
import QtQuick.Controls 2.14
import QtQuick.Window 2.14  

Window {
    visible: true  // this property cause focus lost
    title: "hello world"
  
    Text {
        text: "ttt"
    }
}
```
Thank you :)

**Comment by SavenkovIgor** [comment]
Yes, I catch it occasionally but can't reproduce it. Thanks for the example; I'll try to fix it in a couple of days

**Comment by SavenkovIgor** [comment]
After some research, it was discovered that this issue is reproduced only for the Window component and, in a certain sense, this is normal expected behavior. 

The problem arises specifically when interacting with auto-updates for each code edit. Therefore, I decided to add a toggle to the status bar, which disables the auto-update mode and adds the option to manually redraw the QML WebView with a separate command. 
Also, in addition to the command, if auto-updating is disabled, a button for manual updating appears at the top of code editor
